`timescale 1ns/1ps
//////////////////////////////////////////////////////////////////////////////////
// Project   : Hybrid RC4-Keyed PRESENT-64/80 with RBAC
// Cipher    : PRESENT-64/80  (ISO/IEC 29192-2)
// Target    : Basys3 (Artix-7 xc7a35t)
//
// File      : top_module.v
// Top Module: hybrid_rc4_present
//
// Block size : 64 bits
// Key size   : 80 bits (generated by RC4, 10 bytes)
// Rounds     : 31 (PRESENT standard)
//
// load_sel encoding (SW9..SW8):
//   2'b00 = password   (2 bytes MSB first)
//   2'b01 = plaintext  (8 bytes MSB first)
//   2'b10 = RC4 seed   (8 bytes MSB first)
//
// RBAC:
//   ADMIN = 0xA5C3 -> Encrypt + Decrypt
//   USER  = 0xB2F1 -> Encrypt ONLY
//   WRONG = other  -> Blocked, auth_fail=1
//////////////////////////////////////////////////////////////////////////////////


// ============================================================
//  PRESENT S-Box
// ============================================================
module present_sbox (input [3:0] in, output reg [3:0] out);
    always @(*) begin
        case (in)
            4'h0: out=4'hC; 4'h1: out=4'h5; 4'h2: out=4'h6; 4'h3: out=4'hB;
            4'h4: out=4'h9; 4'h5: out=4'h0; 4'h6: out=4'hA; 4'h7: out=4'hD;
            4'h8: out=4'h3; 4'h9: out=4'hE; 4'hA: out=4'hF; 4'hB: out=4'h8;
            4'hC: out=4'h4; 4'hD: out=4'h7; 4'hE: out=4'h1; 4'hF: out=4'h2;
            default: out=4'h0;
        endcase
    end
endmodule

// ============================================================
//  PRESENT Inverse S-Box
// ============================================================
module present_inv_sbox (input [3:0] in, output reg [3:0] out);
    always @(*) begin
        case (in)
            4'h0: out=4'h5; 4'h1: out=4'hE; 4'h2: out=4'hF; 4'h3: out=4'h8;
            4'h4: out=4'hC; 4'h5: out=4'h1; 4'h6: out=4'h2; 4'h7: out=4'hD;
            4'h8: out=4'hB; 4'h9: out=4'h4; 4'hA: out=4'h6; 4'hB: out=4'h3;
            4'hC: out=4'h0; 4'hD: out=4'h7; 4'hE: out=4'h9; 4'hF: out=4'hA;
            default: out=4'h0;
        endcase
    end
endmodule

// ============================================================
//  PRESENT SubLayer
// ============================================================
module present_sublayer (input [63:0] in, output [63:0] out);
    genvar i;
    generate
        for (i = 0; i < 16; i = i + 1) begin : sbox_gen
            present_sbox sb (.in(in[63-i*4 -: 4]), .out(out[63-i*4 -: 4]));
        end
    endgenerate
endmodule

// ============================================================
//  PRESENT Inverse SubLayer
// ============================================================
module present_inv_sublayer (input [63:0] in, output [63:0] out);
    genvar i;
    generate
        for (i = 0; i < 16; i = i + 1) begin : inv_sbox_gen
            present_inv_sbox isb (.in(in[63-i*4 -: 4]), .out(out[63-i*4 -: 4]));
        end
    endgenerate
endmodule

// ============================================================
//  PRESENT P-Layer (pure wiring)
// ============================================================
module present_player (input [63:0] in, output [63:0] out);
    assign out[63]=in[63]; assign out[62]=in[59]; assign out[61]=in[55]; assign out[60]=in[51];
    assign out[59]=in[47]; assign out[58]=in[43]; assign out[57]=in[39]; assign out[56]=in[35];
    assign out[55]=in[31]; assign out[54]=in[27]; assign out[53]=in[23]; assign out[52]=in[19];
    assign out[51]=in[15]; assign out[50]=in[11]; assign out[49]=in[ 7]; assign out[48]=in[ 3];
    assign out[47]=in[62]; assign out[46]=in[58]; assign out[45]=in[54]; assign out[44]=in[50];
    assign out[43]=in[46]; assign out[42]=in[42]; assign out[41]=in[38]; assign out[40]=in[34];
    assign out[39]=in[30]; assign out[38]=in[26]; assign out[37]=in[22]; assign out[36]=in[18];
    assign out[35]=in[14]; assign out[34]=in[10]; assign out[33]=in[ 6]; assign out[32]=in[ 2];
    assign out[31]=in[61]; assign out[30]=in[57]; assign out[29]=in[53]; assign out[28]=in[49];
    assign out[27]=in[45]; assign out[26]=in[41]; assign out[25]=in[37]; assign out[24]=in[33];
    assign out[23]=in[29]; assign out[22]=in[25]; assign out[21]=in[21]; assign out[20]=in[17];
    assign out[19]=in[13]; assign out[18]=in[ 9]; assign out[17]=in[ 5]; assign out[16]=in[ 1];
    assign out[15]=in[60]; assign out[14]=in[56]; assign out[13]=in[52]; assign out[12]=in[48];
    assign out[11]=in[44]; assign out[10]=in[40]; assign out[ 9]=in[36]; assign out[ 8]=in[32];
    assign out[ 7]=in[28]; assign out[ 6]=in[24]; assign out[ 5]=in[20]; assign out[ 4]=in[16];
    assign out[ 3]=in[12]; assign out[ 2]=in[ 8]; assign out[ 1]=in[ 4]; assign out[ 0]=in[ 0];
endmodule

// ============================================================
//  PRESENT Inverse P-Layer (pure wiring)
// ============================================================
module present_inv_player (input [63:0] in, output [63:0] out);
    assign out[ 0]=in[ 0]; assign out[ 1]=in[16]; assign out[ 2]=in[32]; assign out[ 3]=in[48];
    assign out[ 4]=in[ 1]; assign out[ 5]=in[17]; assign out[ 6]=in[33]; assign out[ 7]=in[49];
    assign out[ 8]=in[ 2]; assign out[ 9]=in[18]; assign out[10]=in[34]; assign out[11]=in[50];
    assign out[12]=in[ 3]; assign out[13]=in[19]; assign out[14]=in[35]; assign out[15]=in[51];
    assign out[16]=in[ 4]; assign out[17]=in[20]; assign out[18]=in[36]; assign out[19]=in[52];
    assign out[20]=in[ 5]; assign out[21]=in[21]; assign out[22]=in[37]; assign out[23]=in[53];
    assign out[24]=in[ 6]; assign out[25]=in[22]; assign out[26]=in[38]; assign out[27]=in[54];
    assign out[28]=in[ 7]; assign out[29]=in[23]; assign out[30]=in[39]; assign out[31]=in[55];
    assign out[32]=in[ 8]; assign out[33]=in[24]; assign out[34]=in[40]; assign out[35]=in[56];
    assign out[36]=in[ 9]; assign out[37]=in[25]; assign out[38]=in[41]; assign out[39]=in[57];
    assign out[40]=in[10]; assign out[41]=in[26]; assign out[42]=in[42]; assign out[43]=in[58];
    assign out[44]=in[11]; assign out[45]=in[27]; assign out[46]=in[43]; assign out[47]=in[59];
    assign out[48]=in[12]; assign out[49]=in[28]; assign out[50]=in[44]; assign out[51]=in[60];
    assign out[52]=in[13]; assign out[53]=in[29]; assign out[54]=in[45]; assign out[55]=in[61];
    assign out[56]=in[14]; assign out[57]=in[30]; assign out[58]=in[46]; assign out[59]=in[62];
    assign out[60]=in[15]; assign out[61]=in[31]; assign out[62]=in[47]; assign out[63]=in[63];
endmodule

// ============================================================
//  PRESENT-64/80 Encrypt (fully unrolled, combinational)
// ============================================================
module present_encrypt (
    input  [63:0] plaintext,
    input  [79:0] key,
    output [63:0] ciphertext
);
    wire [79:0] ks[0:31];
    wire [63:0] rk[0:31];
    wire [63:0] state[0:32];
    assign ks[0] = key;
    genvar r;
    generate
        for (r = 0; r < 31; r = r + 1) begin : keysched
            assign rk[r] = ks[r][79:16];
            wire [79:0] rot = {ks[r][18:0], ks[r][79:19]};
            wire [3:0]  sout;
            present_sbox ks_sb(.in(rot[79:76]), .out(sout));
            wire [4:0] rcon = r + 1;
            assign ks[r+1] = {sout, rot[75:20], rot[19:15]^rcon, rot[14:0]};
        end
    endgenerate
    assign rk[31]   = ks[31][79:16];
    assign state[0] = plaintext ^ rk[0];
    generate
        for (r = 0; r < 31; r = r + 1) begin : rounds
            wire [63:0] after_sub, after_perm;
            present_sublayer sub_u(.in(state[r]),   .out(after_sub));
            if (r < 30) begin
                present_player p_u(.in(after_sub),  .out(after_perm));
                assign state[r+1] = after_perm ^ rk[r+1];
            end else begin
                assign state[r+1] = after_sub ^ rk[r+1];
            end
        end
    endgenerate
    assign ciphertext = state[31];
endmodule

// ============================================================
//  PRESENT-64/80 Decrypt (fully unrolled, combinational)
// ============================================================
module present_decrypt (
    input  [63:0] ciphertext,
    input  [79:0] key,
    output [63:0] plaintext
);
    wire [79:0] ks[0:31];
    wire [63:0] rk[0:31];
    wire [63:0] state[0:32];
    assign ks[0] = key;
    genvar r;
    generate
        for (r = 0; r < 31; r = r + 1) begin : keysched
            assign rk[r] = ks[r][79:16];
            wire [79:0] rot = {ks[r][18:0], ks[r][79:19]};
            wire [3:0]  sout;
            present_sbox ks_sb(.in(rot[79:76]), .out(sout));
            wire [4:0] rcon = r + 1;
            assign ks[r+1] = {sout, rot[75:20], rot[19:15]^rcon, rot[14:0]};
        end
    endgenerate
    assign rk[31]   = ks[31][79:16];
    assign state[0] = ciphertext ^ rk[31];
    generate
        for (r = 0; r < 31; r = r + 1) begin : inv_rounds
            wire [63:0] after_inv_sub, after_inv_perm, after_xor;
            if (r == 0) begin
                present_inv_sublayer isub_u(.in(state[0]),      .out(after_inv_sub));
                assign state[1] = after_inv_sub;
            end else begin
                assign after_xor = state[r] ^ rk[31-r];
                present_inv_player   ip_u  (.in(after_xor),     .out(after_inv_perm));
                present_inv_sublayer isub_u(.in(after_inv_perm), .out(after_inv_sub));
                assign state[r+1] = after_inv_sub;
            end
        end
    endgenerate
    assign plaintext = state[31] ^ rk[0];
endmodule


// ============================================================
//  RC4 Key Stream Generator
//  Input  : 64-bit seed (8 bytes loaded byte-serial)
//  Output : 80-bit keystream (10 bytes) for PRESENT-64/80
// ============================================================
module rc4_keygen (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        start,
    input  wire [63:0] seed,
    output reg  [79:0] key_out,
    output reg         key_valid
);
    localparam IDLE=4'd0, INIT=4'd1, KSA1=4'd2, KSA2=4'd3, KSA3=4'd4,
               PRGA1=4'd5, PRGA2=4'd6, PRGA3=4'd7, DONE=4'd8;

    reg [3:0]  state;
    reg [7:0]  S[0:255];
    reg [7:0]  i, j, si_tmp, sj_tmp, jnew;
    reg [7:0]  pi, pj, pjnew, psi, psj;
    reg [3:0]  pcnt;
    reg [79:0] kbuf;

    reg [7:0] kbyte;
    always @(*) begin
        case (i[2:0])
            3'd0: kbyte=seed[63:56]; 3'd1: kbyte=seed[55:48];
            3'd2: kbyte=seed[47:40]; 3'd3: kbyte=seed[39:32];
            3'd4: kbyte=seed[31:24]; 3'd5: kbyte=seed[23:16];
            3'd6: kbyte=seed[15:8];  3'd7: kbyte=seed[7:0];
            default: kbyte=8'h00;
        endcase
    end

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state<=IDLE; key_valid<=0; key_out<=0; kbuf<=0;
            i<=0; j<=0; pi<=0; pj<=0; pcnt<=0;
        end else begin
            case (state)
                IDLE:  begin key_valid<=0; if(start) begin i<=0; state<=INIT; end end
                INIT:  begin S[i]<=i; if(i==255) begin i<=0; j<=0; state<=KSA1; end else i<=i+1; end
                KSA1:  begin si_tmp<=S[i]; jnew<=j+S[i]+kbyte; state<=KSA2; end
                KSA2:  begin sj_tmp<=S[jnew]; state<=KSA3; end
                KSA3:  begin
                    S[i]<=sj_tmp; S[jnew]<=si_tmp; j<=jnew;
                    if(i==255) begin pi<=1; pj<=0; pcnt<=0; state<=PRGA1; end
                    else begin i<=i+1; state<=KSA1; end
                end
                PRGA1: begin psi<=S[pi]; pjnew<=pj+S[pi]; state<=PRGA2; end
                PRGA2: begin psj<=S[pjnew]; state<=PRGA3; end
                PRGA3: begin
                    S[pi]<=psj; S[pjnew]<=psi; pj<=pjnew;
                    kbuf<={kbuf[71:0], S[psi+psj]};
                    pcnt<=pcnt+1;
                    if(pcnt==9) state<=DONE;
                    else begin pi<=pi+1; state<=PRGA1; end
                end
                DONE:  begin key_out<=kbuf; key_valid<=1; state<=IDLE; end
                default: state<=IDLE;
            endcase
        end
    end
endmodule


// ============================================================
//  CORE MODULE
//  Integrates RC4 + PRESENT-64/80 + RBAC
// ============================================================
module hybrid_rc4_present_core (
    input  wire        clk,
    input  wire        rst_n,
    input  wire [15:0] password_in,
    input  wire        mode_select,
    input  wire [7:0]  rc4_seed_byte,
    input  wire        seed_valid,
    input  wire [63:0] plaintext,
    output reg  [63:0] ciphertext,
    output reg         done,
    output reg         auth_fail
);
    // ---- RBAC ----
    localparam [15:0] PASS_ADMIN = 16'hA5C3;
    localparam [15:0] PASS_USER  = 16'hB2F1;
    localparam [1:0]  ROLE_ADMIN = 2'b11;
    localparam [1:0]  ROLE_USER  = 2'b01;
    localparam [1:0]  ROLE_NONE  = 2'b00;

    reg       auth_ok;
    reg [1:0] role;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            auth_ok<=0; role<=ROLE_NONE; auth_fail<=0;
        end else begin
            case (password_in)
                PASS_ADMIN: begin auth_ok<=1; role<=ROLE_ADMIN; auth_fail<=0; end
                PASS_USER:  begin auth_ok<=1; role<=ROLE_USER;  auth_fail<=0; end
                default:    begin auth_ok<=0; role<=ROLE_NONE;  auth_fail<=1; end
            endcase
        end
    end

    wire enc_ok = auth_ok & role[0];
    wire dec_ok = auth_ok & role[1];
    wire op_ok  = (mode_select==0) ? enc_ok : dec_ok;

    // ---- RC4 Seed Shift Register (8 bytes) ----
    reg [63:0] seed_reg;
    reg [2:0]  seed_cnt;
    reg        rc4_start;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            seed_reg<=64'd0; seed_cnt<=3'd0; rc4_start<=0;
        end else begin
            rc4_start <= 0;
            if (seed_valid && op_ok) begin
                seed_reg <= {seed_reg[55:0], rc4_seed_byte};
                if (seed_cnt==3'd7) begin
                    seed_cnt  <= 3'd0;
                    rc4_start <= 1;
                end else begin
                    seed_cnt <= seed_cnt + 1;
                end
            end
        end
    end

    // ---- RC4 Key Generator ----
    wire [79:0] rc4_key;
    wire        rc4_key_valid;

    rc4_keygen rc4_u (
        .clk      (clk),
        .rst_n    (rst_n),
        .start    (rc4_start),
        .seed     (seed_reg),
        .key_out  (rc4_key),
        .key_valid(rc4_key_valid)
    );

    // ---- Latch PRESENT key ----
    reg [79:0] present_key;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) present_key<=80'd0;
        else if (rc4_key_valid && op_ok) present_key<=rc4_key;
    end

    // ---- PRESENT Datapath ----
    wire [63:0] enc_out, dec_out;
    present_encrypt enc_u(.plaintext(plaintext),  .key(present_key), .ciphertext(enc_out));
    present_decrypt dec_u(.ciphertext(plaintext), .key(present_key), .plaintext(dec_out));

    // ---- Output Register ----
    reg key_valid_d;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            key_valid_d<=0; done<=0; ciphertext<=64'd0;
        end else begin
            key_valid_d <= rc4_key_valid;
            done        <= 0;
            if (key_valid_d && op_ok) begin
                done <= 1;
                if      (mode_select==0 && enc_ok) ciphertext <= enc_out;
                else if (mode_select==1 && dec_ok) ciphertext <= dec_out;
                else                               ciphertext <= 64'd0;
            end
        end
    end

endmodule


// ============================================================
//  TOP MODULE — Byte-Serial Basys3 Interface
//
//  load_sel (SW9..SW8):
//    2'b00 = password   2 bytes MSB first
//    2'b01 = plaintext  8 bytes MSB first
//    2'b10 = RC4 seed   8 bytes MSB first
//
//  out_byte_sel (SW12..SW10): byte 0=MSB .. 7=LSB
//
//  Basys3 pins:
//    clk=W5  rst_n=U18(BTNC)  wr_en=BTNL
//    data_in=SW7..0  load_sel=SW9..8
//    mode_select=SW15  out_byte_sel=SW12..10
//    data_out=LD7..0  done=LD14  auth_fail=LD15
// ============================================================
module hybrid_rc4_present (
    input  wire       clk,
    input  wire       rst_n,
    input  wire [7:0] data_in,
    input  wire [1:0] load_sel,
    input  wire       wr_en,
    input  wire       mode_select,
    input  wire [2:0] out_byte_sel,
    output wire [7:0] data_out,
    output wire       done,
    output wire       auth_fail
);
    // ---- Password shift register (2 bytes) ----
    reg [15:0] pwd_reg;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) pwd_reg<=16'd0;
        else if (wr_en && load_sel==2'b00)
            pwd_reg <= {pwd_reg[7:0], data_in};
    end

    // ---- Plaintext shift register (8 bytes) ----
    reg [63:0] pt_reg;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) pt_reg<=64'd0;
        else if (wr_en && load_sel==2'b01)
            pt_reg <= {pt_reg[55:0], data_in};
    end

    wire seed_valid_w = (wr_en && load_sel==2'b10);
    wire [63:0] ciphertext_w;

    hybrid_rc4_present_core core_u (
        .clk          (clk),
        .rst_n        (rst_n),
        .password_in  (pwd_reg),
        .mode_select  (mode_select),
        .rc4_seed_byte(data_in),
        .seed_valid   (seed_valid_w),
        .plaintext    (pt_reg),
        .ciphertext   (ciphertext_w),
        .done         (done),
        .auth_fail    (auth_fail)
    );

    // ---- Output byte mux ----
    reg [7:0] data_out_r;
    always @(*) begin
        case (out_byte_sel)
            3'd0: data_out_r=ciphertext_w[63:56]; 3'd1: data_out_r=ciphertext_w[55:48];
            3'd2: data_out_r=ciphertext_w[47:40]; 3'd3: data_out_r=ciphertext_w[39:32];
            3'd4: data_out_r=ciphertext_w[31:24]; 3'd5: data_out_r=ciphertext_w[23:16];
            3'd6: data_out_r=ciphertext_w[15:8];  3'd7: data_out_r=ciphertext_w[7:0];
            default: data_out_r=8'd0;
        endcase
    end
    assign data_out = data_out_r;

endmodule
